### ISSUE TITLE
Add Additional Off-Screen Text to Bookmarklets Links

### ISSUE THREAD

**Issue by jfc3** [pauljadam/bookmarklets#2]
URL - http://pauljadam.com/bookmarklets/

Here is a recommendation to help screen reader users why not add additional off-screen text to the links that tell  them this is an example page and the other is the tool. 

An example might be the following with off-screen text in the brackets "**[**" "**]**" and **bold**:

Landmarks [**examples page**] (Landmarks [**bookmarklet**])

Or you could place them in and accessible TABLE with the table headings being "**Example Page**" and "**Bookmarklet**" along with the off-screen text so it's easier to tell what's going on. Also the the TABLE CAPTION can explain things for people.

**Comment by pauljadam** [comment]
Hi @jfc3 thanks for the feedback! I prefer not to use visually hidden text and aria-label modification would require more code.

I like your idea of a data table, it provides all the semantics we need and looks good visually. I updated the page and updated all the bookmarklets with code from the Safari Extension counterpart. Thanks!
